# Generated by Django 5.0.6 on 2024-08-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ('-create_datetime',), 'verbose_name': 'Logs', 'verbose_name_plural': 'Logs'},
        ),
    ]
