# Generated by Django 5.0.6 on 2024-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('purple', 'purple'), ('green', 'green'), ('red', 'red')], null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
