# Generated by Django 5.0.6 on 2024-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('purple', 'purple'), ('green', 'green'), ('red', 'red')], max_length=200, null=True),
        ),
    ]
