# Generated by Django 5.0.6 on 2024-07-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_mgmt', '0002_column_color_alter_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
