name: CI/CD for Docker Image
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production


    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (or other container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env dynamically
        run: |
          # Create .env from example.env
          echo "Generating .env file..."
          
          # Read example.env line by line
          while IFS= read -r line
          do
            # Skip empty lines
            [ -z "$line" ] && continue

            # Extract the key name from the line (before =)
            key=$(echo "$line" | cut -d '=' -f 1)

            # Get value from GitHub environment or secret
            value="${{ secrets[key] }}"  # fallback to secrets
            if [ -z "$value" ]; then
              value="${{ env[key] }}"
            fi

            # Replace line with key=value
            echo "$key=$value" >> .env
          done < example.env

          echo ".env generated successfully."
       
      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag 7721110/tms:latest --build-arg ENV_FILE=.env

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: docker push 7721110/tms:latest
