jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # <- this exposes your environment secrets & variables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env dynamically
        run: |
          echo "Generating .env from example.env..."
          envsubst < example.env > .env
          echo ".env generated successfully"

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag 7721110/tms:latest

      - name: Push Docker image
        run: docker push 7721110/tms:latest
