name: CI/CD for Docker Image
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production


    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (or other container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate .env dynamically
        run: |
          # Create .env from example.env
          envsubst < example.env > .env
          echo ".env generated successfully."
        env:
          SECREAT_KEY: ${{ secrets.SECREAT_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DEBUG: ${{ secrets.DEBUG }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          TINYMCE_API_KEY: ${{ secrets.TINYMCE_API_KEY }}
       
      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag 7721110/tms:latest --build-arg ENV_FILE=.env

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: docker push 7721110/tms:latest
